/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The main heading displayed above the heatmap. Use to describe what data relationship is being visualized.
 */
export type Title = string;
/**
 * Secondary text displayed below the title. Use for additional context like data source, time period, or measurement units.
 */
export type Subtitle = string;
/**
 * Label text displayed below the horizontal axis. Describes what the x-dimension represents (e.g., 'Hour of Day', 'Category').
 */
export type XAxisLabel = string;
/**
 * Label text displayed beside the vertical axis. Describes what the y-dimension represents (e.g., 'Day of Week', 'Sensor ID').
 */
export type YAxisLabel = string;
/**
 * When enabled, displays a color scale legend showing the mapping between colors and heat values.
 */
export type ShowLegend = boolean;
/**
 * The lower bound of the heat scale. Values at or below this will be colored with the first color in the heat colors array. Set based on your data's expected minimum.
 */
export type MinValue = number;
/**
 * The upper bound of the heat scale. Values at or above this will be colored with the last color in the heat colors array. Set based on your data's expected maximum.
 */
export type MaxValue = number;
/**
 * When enabled, colors blend smoothly as a continuous gradient between defined colors. When disabled, colors appear as discrete blocks with sharp boundaries.
 */
export type Continuous = boolean;
/**
 * When enabled, displays the numeric heat value inside each cell. Useful for precise reading but may clutter dense heatmaps.
 */
export type ShowValues = boolean;
/**
 * Array of colors defining the heat scale gradient, from lowest to highest values. Common patterns: blue-to-red for temperature, white-to-dark for intensity, green-yellow-red for status.
 */
export type HeatColors = Color[];
/**
 * The name identifier for this data series. Used in tooltips and legends.
 */
export type Label = string;
/**
 * The horizontal axis category or value for this data point (e.g., hour number, category name).
 */
export type XValue = string;
/**
 * The vertical axis category or value for this data point (e.g., day name, sensor ID).
 */
export type YValue = string;
/**
 * The numeric intensity value that determines the cell color based on the heat color scale.
 */
export type HeatValue = number;
/**
 * Column value used to split data into multiple heatmaps. Each unique value creates a separate chart (e.g., split by region to show one heatmap per region).
 */
export type SplitDataBy = string;
/**
 * Array of data points. Each point specifies its x position, y position, and heat value.
 */
export type Data = {
    x?: XValue;
    y?: YValue;
    heat?: HeatValue;
    pivot?: SplitDataBy;
    [k: string]: unknown;
}[];
/**
 * Array of data series configurations. Each series provides the data points for the heatmap grid.
 */
export type Dataseries = {
    label?: Label;
    data?: Data;
    [k: string]: unknown;
}[];

/**
 * A heatmap chart widget for visualizing data intensity across two categorical or ordinal dimensions. Use this widget to display patterns in data such as activity over time, correlation matrices, geographic data density, or any metric that varies across two axes. Colors represent value intensity from minimum to maximum, with optional continuous gradient or discrete block rendering. Ideal for identifying patterns, anomalies, and trends in multi-dimensional data.
 */
export interface HeatmapConfiguration {
    title?: Title;
    subTitle?: Subtitle;
    axis?: AxisSettings;
    heatMap?: HeatSettings;
    dataseries?: Dataseries;
    [k: string]: unknown;
}
/**
 * Configuration for the chart axes and legend display.
 */
export interface AxisSettings {
    xAxisLabel?: XAxisLabel;
    yAxisLabel?: YAxisLabel;
    showLegend?: ShowLegend;
    [k: string]: unknown;
}
/**
 * Configuration for the heatmap color mapping and value display.
 */
export interface HeatSettings {
    min?: MinValue;
    max?: MaxValue;
    continuous?: Continuous;
    showValues?: ShowValues;
    colors?: HeatColors;
    [k: string]: unknown;
}
/**
 * A color in the gradient scale. Add multiple colors for richer gradients (e.g., blue → yellow → red).
 */
export interface Color {
    [k: string]: unknown;
}
